### PR TITLE
Fix for tiamo/spss#30

### PR DESCRIPTION
**Pull request by mennodekker**
Reading the VeryLongString still inserts a blank after each 255 byte segment in the data so the unit test fails. I have no time to fix that now but writing seems the most important thing. 

I checked in SPSS 25 and I cound open the produced file.

### CODE REVIEW

**Comment by mennodekker** [comment]
@tiamo I have the longstring reading and writing working now. Also included a unit test. Please have a look and merge if you think it is good enough. If not, please let me know

**Comment by mennodekker** [comment]
@tiamo I fixed the broken unit test, it only failed for php 5.5 that probably has a different mb_internal_encoding()

Anyway, I think the very long string implementation for strings > 255 bytes is now working well. Could you review this please?

**Comment by imlcl** [comment]
It seems like very cool 👍

**Comment by tiamo** [comment]
Thank you @mennodekker for contribution!

**Pull request merged**
