### PR TITLE
Read and write data by cases (RFC). Close #43

### LINKED ISSUE #43: Read/Write the data on demand by case (row).
Actually we are reading/writing the whole data file in a matrix at once and this is not ideally when we have big files. One idea is provide an API to set the buffer in the position where the case start and read that case only. Of course when the file is compressed all cases size are different, so... This will required just read the position in the file where the case is, instead of read the real case at once. Then on demand, we can go to that position in the file and read the case that we want.

**Please note:** If the data is not compress we don't need to iterate  the file on the load, as all cases have the same size, so we can predict where the case start.

```php
$casePosition = //Is an array that will be filled when the data is loaded, instead of fill the matrix. 
```

Then if we want just a case:

```php
$buffer->setPosition($casePosition[$case]);
return $buffer->readCase(); //This is an array.
```

and we can iterate for all cases if we want the whole file:

```php
for ($case = 0; $case<count($casePosition); $case++) {
     $buffer->setPosition($casePosition[$case]);
     $matrix[$case] = $buffer->readCase();
}
return $matrix;
```

To write the file is also useful that can be done case by case instead of the whole info at once.

### PR DESCRIPTION
**Pull request by lestcape**
This add the possibility to read and write data by cases, without to add much more complexity.

The good think is that you don't need to have the whole data loaded at once in RAM, you can just have your file metadata and the current case only.

In my opinion, the problem with this implementation is that is not possible move the buffer to the case you want. So. you are forced to read/write the data in the order that they come from your provider. Resolve the problematic of move the buffer to the case you want it's complex and will add much more memory to you RAM and also will slow down the performance to read/write the data.

Some code that are not landed yet:

- We don' t need to override the whole header to add a new case, is just only needed override he number of records in the header session as this information is in the same position always.

- We don' t need to have both ways to read and write files as this create confusion.

### CODE REVIEW

**Comment by tiamo** [comment]
Thanks for your pull request, I'll check it as soon as possible. Could you check why tests was not passed?

**Comment by lestcape** [comment]
> Could you check why tests was not passed?

I think there are a difference in the generated data.sav file. The file that generate the new procedure is not the same as the existing file of the example. Anyway, if i regenerate the file using the current procedure, i get the same file that i get using the new procedure. So, my theory is one of this two possibilities:

1. The current file is not in correspondence with the current implementation.
2. There are differences between generate the file in Linux than do it in Windows and the current file was generated in Windows, while the file that I regenerated was from Linux.

**Comment by lestcape** [comment]
Ok,I found the cause of the problem. Is the issue https://github.com/tiamo/spss/issues/46. The file data.sav was generated before exclude the` writeBlank `line and as i'm here generating the file without that line, there are a difference of both file generation.

 In fact, if in the master version you execute the write.php example and then you try to execute the read.php example, you will see that you can not read what you are generating.

**Comment by lestcape** [comment]
So, please merge https://github.com/tiamo/spss/pull/47 and then we can evaluate if this continues failing after that. It's to me difficult see if there are any other problem if this is not fixed first.

**Comment by imlcl** [comment]
Wow, Is this the spss appending mode?

**Comment by lestcape** [comment]
@imlcl it's not properly this feature, but i think that you can convert it easy in that if it's what you want. Your appening mode implementation seem to be something that should work with an arbitrary number of cases (rows) and with this implementation you can only append one case at time. 

Anyway if you ask me, you implementation complicate a lot the appending mode, because you are playing with more than one sav file at time and my vision is not append one file to another, but instead append data (a case) to the file.

**Pull request merged**
