### PR TITLE
Skip invalid record for variables computation.

### PR DESCRIPTION
**Pull request by lestcape**
We are adding variables for records that are not really variables. This ending in conflicts of all types... So, all that problems should be avoided and then we need to return a clean data to the user (api consumers). Users don't need / want to know the internal representation of the sav file format at all.

As consequence, what this pull is doing then is skipping from the variables computation this type of records:

-  Blank records ([See the equivalent in pssp](https://github.com/gitGNU/gnu_pspp/blob/master/src/data/sys-file-reader.c#L1519)).
-  Records that was added only because a Long Strings variable was occurred ([See the equivalent in pssp](https://github.com/gitGNU/gnu_pspp/blob/master/src/data/sys-file-reader.c#L1413-L1414)).

~~**TODO:** Please note that this fix all test cases except the MachineFloatingPointTest that will need an special fix later.~~ This was because i have not installed the php-bcmath package.

### CODE REVIEW

**Comment by lestcape** [comment]
Please note, the last 3 commits was to be possible recovered the ValueLabels from the filter variables and now we have two possibilities inside the `ValueLabel` class.

1. Check if a `variable` have a `ValueLabel` using the `variables` property of the `ValueLabel` object:

```php
    /**
     * @param Variable $variable
     */
    public function haveVar($variable)
    {
        foreach ($this->indexes as $index) {
            if($this->variables[$index] == $variable) {
                return true;
            }
        }
        return false;
    }
```

2. Check if a `variable` have a `ValueLabel` using the `realPosition` property of the `ValueLabel` object:

```php
    /**
     * @param Variable $variable
     */
    public function haveVar($variable)
    {
        foreach ($this->indexes as $index) {
            if($index == $variable=>realPosition) {
                return true;
            }
        }
        return false;
    }
```

**Comment by imlcl** [comment]
what's the meaning about this PR?
I want to update tiamo/spss，should I manual merge this PR for my update?

**Comment by lestcape** [comment]
> What's the meaning about this PR?

Please see this merge request: https://github.com/tiamo/spss/pull/47. Without that, if you try to create a sav file and then you try to read it using this library your procedure will fail. Also the pspp software will fail to read the file that was created by this library. This is why that pull was merged, because adding that spaces fixed the problem of both cases (So, the spaces are a requirement).

Without to much details, if you add the blank spaces in the file when is create, this mean that you need to remove the spaces when you read the file, if you want the same result. Anyway, this are not the only places where the blank spaces are added when the sav file is created (with this library or not). Then, how it's pretty difficult detect what is the real cause of an space when you read an arbitrary sav file we have a problem.

**Context:** 
Initially this library was conceived to read the file and also create empty "spaces" as it was read. But how now there are other empty spaces in the file the real data index was moved to other different position. This finally is the cause that most of test cases of the library currently fail. I try to address this problem in this pull https://github.com/tiamo/spss/pull/50, moving the position where the test cases read the data, but this is not a properly solution, because is like forced the tests to return what i want and of course this is wrong.

So, in this current pull i just simple remove all empty spaces from all places and then I create an index for ONLY the valid data. The result is to have a different organization of the data (indexes) of how it was before. Because before, the library was adding (indexing) blank spaces.

Then i suppose that probably as this library was used in some application by the original author, this pull break his work some where and he is thinking what he will do with that. Otherwise he have not time right now to take a look.

> I want to update tiamo/spss，should I manual merge this PR for my update?

I can not answer that.

**Comment by lestcape** [comment]
Probably you have here one example of what this pull is resolving: https://github.com/tiamo/spss/issues/38

**Comment by tiamo** [comment]
@lestcape Thank you for your contribution! Sorry for my late reply, I didn't have free time to check it.

**Pull request merged**
