### PR TITLE
Fixed really long strings

### PR DESCRIPTION
**Pull request by SamMousa**
I'm having issues with really long strings in SPSS 20.

Specifically the variables don't get stitched back together by SPSS resulting in ~20 variables of 255 chars instead of just one.
This PR just has an altered test file, to create an SPSS File that doesn't work properly...

### CODE REVIEW

**Comment by SamMousa** [comment]
Specifically, length > 503 seems to break the stitching...

**Comment by SamMousa** [comment]
[samples.zip](https://github.com/tiamo/spss/files/3790409/samples.zip)

This zip contains 2 samples, open at your own risk, GitHub does not support `.sav` and you should generally be careful when opening untrusted files ^^

**Comment by mennodekker** [comment]
Can you check #45 ? I had problems with the internal variable names, but at least it seems to produce a good file for me when I used 520 width. Bytewise there are some differences I can not explain.

**Comment by SamMousa** [comment]
Seems to work!

**Comment by SamMousa** [comment]
@mennodekker I have incorporated your fix in this PR.
I have also done some more extensive testing and think I now understand how SPSS uses the variable names.

Specifically segment variables must share a prefix with the primary variable. Combined with the fact that SPSS will rename variables with duplicate names this causes issues.

This PR uses an approach to recode variables only when required while keeping the required 5 character prefix.

When you have the time could you confirm that this works correctly for you as well?
@tiamo I think this is ready to be merged!

**Comment by SamMousa** [comment]
@tiamo are you still actively maintaining or should I just fork and maintain my own version?

**Pull request closed without merging**
